name: Build and Deploy

# Set permissions for the GitHub token
permissions:
  contents: write

env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "saadpasta" # Replace with your Medium username

on:
  workflow_dispatch: # Manual trigger
  push: # Trigger on pushes to the master branch
    branches:
      - master
  schedule: # Scheduled trigger (e.g., every Monday at 12:00 PM)
    - cron: "0 12 * * 1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Required for deployment

      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Update npm ğŸš€
        run: npm install -g npm@latest

      - name: Install and Build ğŸ”§ # Install dependencies and build the project
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
          BRANCH: gh-pages # Deployment branch
          FOLDER: build # Deployment folder
